[package]
name = "mailz-mcp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mailz-mcp"
path = "src/main.rs"

[dependencies]
mailz-core.workspace = true
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
schemars = "1.2"
